version: "3.9" 
services:
  mysql:
    image: percona/percona-xtradb-cluster:8.0.21
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - CLUSTER_NAME=test
    volumes:
      - ${PWD}/init.sql:/init.sql
    command: "--default-authentication-plugin=mysql_native_password --init-file=/init.sql --gtid_mode=ON --session_track_gtids=OWN_GTID --enforce_gtid_consistency"

  proxysql:
    image: proxysql/proxysql:2.0.15
    ports:
      - "6033:6033"
      - "6032:6032"
    volumes:
      - ${PWD}/proxysql.cnf:/etc/proxysql.cnf
    depends_on:
    - mysql
    links:
    - mysql